version: '3'
services:
  ui:
    image: nginx:1.25.2-alpine
    container_name: ui-beta
    restart: unless-stopped

    depends_on:
      - backend
    volumes:
      - /build:/usr/share/nginx/html
      - /config/nginx/nginx-beta.conf:/etc/nginx/nginx.conf:ro
      - /config/nginx/htpasswd:/etc/nginx/htpasswd:ro
    networks:
      bridge-beta:
        ipv4_address: 172.2.0.3

  db:
    image: postgres:15.3
    container_name: hcs-db-beta
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      bridge-beta:
        ipv4_address: 172.2.0.5

  backend:
    image: backend-master:latest
    container_name: backend-beta
    restart: unless-stopped
    depends_on:
      - db
    networks:
      bridge-beta:
        ipv4_address: 172.2.0.4
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=db_user
      - DB_PASSWORD=passwd

volumes:
  db-data:

networks:
  bridge-beta:
    external: true
